
DROP TABLE IF EXISTS posts;

CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    option TEXT NOT NULL,
    email TEXT NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL
);